In [524]:
import numpy as np
import cirq
from scipy.linalg import svd

In [2]:
print(cirq.google.Bristlecone)

                                             (0, 5)────(0, 6)
                                             │         │
                                             │         │
                                    (1, 4)───(1, 5)────(1, 6)────(1, 7)
                                    │        │         │         │
                                    │        │         │         │
                           (2, 3)───(2, 4)───(2, 5)────(2, 6)────(2, 7)───(2, 8)
                           │        │        │         │         │        │
                           │        │        │         │         │        │
                  (3, 2)───(3, 3)───(3, 4)───(3, 5)────(3, 6)────(3, 7)───(3, 8)───(3, 9)
                  │        │        │        │         │         │        │        │
                  │        │        │        │         │         │        │        │
         (4, 1)───(4, 2)───(4, 3)───(4, 4)───(4, 5)────(4, 6)────(4, 7)───(4, 8)───(4, 9)───(4, 10)
         │        │      

In [7]:
q0 = cirq.NamedQubit("0")
q1 = cirq.NamedQubit("1")
q2 = cirq.NamedQubit("2")
q3 = cirq.NamedQubit("3")

ops = [cirq.H(q0), cirq.H(q1), cirq.CNOT(q1, q2), cirq.CNOT(q0, q3), cirq.H(q1)]
circuit = cirq.Circuit(ops)
print(circuit)

          ┌──┐
0: ───H─────@────────
            │
1: ───H────@┼────H───
           ││
2: ────────X┼────────
            │
3: ─────────X────────
          └──┘


In [13]:
for i, moment in enumerate(circuit):
    print(moment)

  ╷ None
╶─┼──────
0 │ H
  │
1 │ H
  │
  ╷ None
╶─┼──────
0 │ @
  │ │
1 │ @
  │ │
2 │ X
  │ │
3 │ X
  │
  ╷ None
╶─┼──────
1 │ H
  │


In [14]:
print(repr(circuit))

cirq.Circuit([
    cirq.Moment(
        cirq.H(cirq.NamedQubit('0')),
        cirq.H(cirq.NamedQubit('1')),
    ),
    cirq.Moment(
        cirq.CNOT(cirq.NamedQubit('1'), cirq.NamedQubit('2')),
        cirq.CNOT(cirq.NamedQubit('0'), cirq.NamedQubit('3')),
    ),
    cirq.Moment(
        cirq.H(cirq.NamedQubit('1')),
    ),
])


In [15]:
print(cirq.google.Sycamore)

                                             (0, 5)───(0, 6)
                                             │        │
                                             │        │
                                    (1, 4)───(1, 5)───(1, 6)───(1, 7)
                                    │        │        │        │
                                    │        │        │        │
                           (2, 3)───(2, 4)───(2, 5)───(2, 6)───(2, 7)───(2, 8)
                           │        │        │        │        │        │
                           │        │        │        │        │        │
                  (3, 2)───(3, 3)───(3, 4)───(3, 5)───(3, 6)───(3, 7)───(3, 8)───(3, 9)
                  │        │        │        │        │        │        │        │
                  │        │        │        │        │        │        │        │
         (4, 1)───(4, 2)───(4, 3)───(4, 4)───(4, 5)───(4, 6)───(4, 7)───(4, 8)───(4, 9)
         │        │        │        │        │        │   

In [17]:
for i in range(0, 11):
    print(int(1 / 4 * (4 ** i - 3 * i - 1)))

0
0
2
13
60
252
1019
4090
16377
65529
262136


In [20]:
print(*(cirq.LineQubit.range(2)))

0 1


In [59]:
xx = cirq.google.SycamoreGate()(cirq.GridQubit(3,3), cirq.GridQubit(3, 4))
converter = cirq.google.ConvertToSycamoreGates()
xx = converter.convert(xx)
c = cirq.Circuit(xx)
c = cirq.google.optimized_for_sycamore(c)

print(c)



(3, 3): ───PhXZ(a=-0.25,x=0,z=0.75)───iSwap────────PhXZ(a=-1,x=0,z=-0.5)───iSwap────────PhXZ(a=-0.167,x=0.042,z=0.167)───iSwap────────PhXZ(a=-1,x=0.118,z=0)───iSwap───────PhXZ(a=0,x=0.042,z=0)───
                                      │                                    │                                             │                                     │
(3, 4): ───PhXZ(a=0.25,x=0,z=0.25)────iSwap^-0.5───PhXZ(a=-1,x=0,z=-0.5)───iSwap^-0.5───PhXZ(a=0.333,x=0.5,z=-0.333)─────iSwap^-0.5────────────────────────────iSwap^0.5───PhXZ(a=-1,x=0.5,z=0)────


In [54]:
print(c)

(3, 3): ───SYC───
           │
(3, 4): ───SYC───


In [69]:
xx = cirq.google.SycamoreGate().on(cirq.GridQubit(3,3), cirq.GridQubit(3, 4))
c = cirq.Circuit(xx)
converter = cirq.google.ConvertToSycamoreGates()
c = converter.convert(c)
c = cirq.google.optimized_for_sycamore(c)

print(c)

AttributeError: 'GateOperation' object has no attribute 'operations'

In [70]:
g = cirq.google.SycamoreGate().on(cirq.GridQubit(0, 0), cirq.GridQubit(0, 1))
g = converter.convert(g)
c = cirq.Circuit(g)
c = cirq.google.optimized_for_sycamore(c)
print(c)

(0, 0): ───PhXZ(a=-0.25,x=0,z=0.75)───iSwap────────PhXZ(a=-1,x=0,z=-0.5)───iSwap────────PhXZ(a=-0.167,x=0.042,z=0.167)───iSwap────────PhXZ(a=-1,x=0.118,z=0)───iSwap───────PhXZ(a=0,x=0.042,z=0)───
                                      │                                    │                                             │                                     │
(0, 1): ───PhXZ(a=0.25,x=0,z=0.25)────iSwap^-0.5───PhXZ(a=-1,x=0,z=-0.5)───iSwap^-0.5───PhXZ(a=0.333,x=0.5,z=-0.333)─────iSwap^-0.5────────────────────────────iSwap^0.5───PhXZ(a=-1,x=0.5,z=0)────


In [79]:
gate = cirq.CZ
target_qubits = [cirq.GridQubit(0,0), cirq.GridQubit(0, 1)]#, cirq.GridQubit(1, 0), cirq.GridQubit(1, 1)]
g = gate.on(*target_qubits)
c = cirq.Circuit(g)
c = converter.convert(c)
#c = cirq.google.optimized_for_sycamore(c, optimizer_type="sycamore")

In [80]:
print(c)

[cirq.PhasedXPowGate(phase_exponent=0.5678998743900456, exponent=0.5863459345743176).on(cirq.GridQubit(0, 0)), cirq.PhasedXPowGate(phase_exponent=0.3549946157441739).on(cirq.GridQubit(0, 1)), cirq.google.SYC(cirq.GridQubit(0, 0), cirq.GridQubit(0, 1)), cirq.PhasedXPowGate(phase_exponent=-0.5154334589432878, exponent=0.5228733015013345).on(cirq.GridQubit(0, 1)), cirq.PhasedXPowGate(phase_exponent=0.06774925307475355).on(cirq.GridQubit(0, 0)), cirq.google.SYC(cirq.GridQubit(0, 0), cirq.GridQubit(0, 1)), cirq.PhasedXPowGate(phase_exponent=-0.5987667922766213, exponent=0.4136540654256824).on(cirq.GridQubit(0, 0)), (cirq.Z**-0.9255092746611595).on(cirq.GridQubit(0, 1)), (cirq.Z**-1.333333333333333).on(cirq.GridQubit(0, 0))]


In [88]:
gbare = cirq.ControlledGate(cirq.CCX).on(*(cirq.LineQubit.range(4)))
g = gbare._decompose_()

In [89]:
holder = []
for dg in g:
    holder.extend(dg._decompose_())

In [90]:
print(holder)

[(cirq.Y**0.5).on(cirq.LineQubit(3)).controlled_by(cirq.LineQubit(0)), cirq.XPowGate(exponent=1.0, global_shift=-0.25).on(cirq.LineQubit(3)).controlled_by(cirq.LineQubit(0)), cirq.T(cirq.LineQubit(1)).controlled_by(cirq.LineQubit(0)), cirq.T(cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0)), cirq.T(cirq.LineQubit(3)).controlled_by(cirq.LineQubit(0)), cirq.CNOT(cirq.LineQubit(1), cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0)), cirq.CNOT(cirq.LineQubit(2), cirq.LineQubit(3)).controlled_by(cirq.LineQubit(0)), (cirq.T**-1).on(cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0)), cirq.T(cirq.LineQubit(3)).controlled_by(cirq.LineQubit(0)), cirq.CNOT(cirq.LineQubit(1), cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0)), cirq.CNOT(cirq.LineQubit(2), cirq.LineQubit(3)).controlled_by(cirq.LineQubit(0)), (cirq.T**-1).on(cirq.LineQubit(3)).controlled_by(cirq.LineQubit(0)), cirq.CNOT(cirq.LineQubit(1), cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0)), cirq.CNOT(cirq.LineQubit(2), cirq.Lin

In [164]:
def keep_func(gate):
    if cirq.unitary(gate).shape[0] < 5:
        return True
    else:
        return False
cirq.decompose(gbare, keep=keep_func)

ValueError: Operation doesn't satisfy the given `keep` but can't be decomposed: cirq.CZ(cirq.LineQubit(1), cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0))

In [132]:
toffoli = cirq.ControlledGate(cirq.CZ)(*(cirq.LineQubit.range(3)))
cirq.decompose(toffoli, keep = keep_func)

ValueError: Operation doesn't satisfy the given `keep` but can't be decomposed: cirq.CZ(cirq.LineQubit(1), cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0))

In [100]:
diag = cirq.DiagonalGate(toffoli)

AttributeError: module 'cirq' has no attribute 'DiagonalGate'

In [116]:
print(repr(toffoli))
print(toffoli)

cirq.CZ(cirq.LineQubit(1), cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0))
CCZ(0, 1, 2)


In [113]:
toffoli = cirq.CCZ(*(cirq.LineQubit.range(3)))
cirq.decompose(toffoli, keep = keep_func)

[cirq.T(cirq.LineQubit(0)),
 cirq.T(cirq.LineQubit(1)),
 cirq.T(cirq.LineQubit(2)),
 cirq.CNOT(cirq.LineQubit(0), cirq.LineQubit(1)),
 cirq.CNOT(cirq.LineQubit(1), cirq.LineQubit(2)),
 (cirq.T**-1).on(cirq.LineQubit(1)),
 cirq.T(cirq.LineQubit(2)),
 cirq.CNOT(cirq.LineQubit(0), cirq.LineQubit(1)),
 cirq.CNOT(cirq.LineQubit(1), cirq.LineQubit(2)),
 (cirq.T**-1).on(cirq.LineQubit(2)),
 cirq.CNOT(cirq.LineQubit(0), cirq.LineQubit(1)),
 cirq.CNOT(cirq.LineQubit(1), cirq.LineQubit(2)),
 (cirq.T**-1).on(cirq.LineQubit(2)),
 cirq.CNOT(cirq.LineQubit(0), cirq.LineQubit(1)),
 cirq.CNOT(cirq.LineQubit(1), cirq.LineQubit(2))]

In [122]:
g = cirq.ControlledGate(cirq.CCZ).on(*(cirq.LineQubit.range(4)))
cirq.decompose(g, keep=keep_func)

[cirq.T(cirq.LineQubit(1)).controlled_by(cirq.LineQubit(0)),
 cirq.T(cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0)),
 cirq.T(cirq.LineQubit(3)).controlled_by(cirq.LineQubit(0)),
 cirq.CNOT(cirq.LineQubit(1), cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0)),
 cirq.CNOT(cirq.LineQubit(2), cirq.LineQubit(3)).controlled_by(cirq.LineQubit(0)),
 (cirq.T**-1).on(cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0)),
 cirq.T(cirq.LineQubit(3)).controlled_by(cirq.LineQubit(0)),
 cirq.CNOT(cirq.LineQubit(1), cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0)),
 cirq.CNOT(cirq.LineQubit(2), cirq.LineQubit(3)).controlled_by(cirq.LineQubit(0)),
 (cirq.T**-1).on(cirq.LineQubit(3)).controlled_by(cirq.LineQubit(0)),
 cirq.CNOT(cirq.LineQubit(1), cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0)),
 cirq.CNOT(cirq.LineQubit(2), cirq.LineQubit(3)).controlled_by(cirq.LineQubit(0)),
 (cirq.T**-1).on(cirq.LineQubit(3)).controlled_by(cirq.LineQubit(0)),
 cirq.CNOT(cirq.LineQubit(1), cirq.LineQubit(2))

In [123]:
x = str(repr(toffoli))

In [124]:
print(x)

cirq.CZ(cirq.LineQubit(1), cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0))


In [140]:
x = cirq.
print(cirq.unitary(cirq.CCX))

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j]]


In [127]:
test = cirq.CCX
test = cirq.decompose(test, keep=keep_func)

TypeError: _decompose_() missing 1 required positional argument: 'qubits'

In [134]:

print(*(toffoli.qubits))

0 1 2


In [136]:
n_qubits = 5
input = np.empty((2 ** n_qubits, 2 ** n_qubits))
input[1:] = np.eye(2 ** n_qubits)[:-1]
input[:1] = np.eye(2 ** n_qubits)[-1:]
print(input)

[[0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [139]:
print(cirq.Circuit(toffoli))
print(cirq.CCX)

0: ───@───
      │
1: ───@───
      │
2: ───@───
TOFFOLI


In [141]:
x = cirq.ControlledGate(cirq.ControlledGate(cirq.CCX)).on(*cirq.LineQubit.range(5))

In [142]:
print(cirq.Circuit(x))

0: ───@───
      │
1: ───@───
      │
2: ───@───
      │
3: ───@───
      │
4: ───X───


In [148]:
def increment_circuit(qubits):
    n_qubits = len(qubits)
    for i in range(n_qubits):
        gate = cirq.X
        for j in range(n_qubits - i - 1):
            gate = cirq.ControlledGate(gate)
        op = gate.on(*qubits[:n_qubits - i])
        yield op            
            

In [151]:
qubits = cirq.GridQubit.square(int(np.sqrt(9)), 3, 3)
# qubits = cirq.LineQubit.range(5)
c = cirq.Circuit(increment_circuit(qubits))
print(c)

(3, 3): ───@───@───@───@───@───@───@───@───X───
           │   │   │   │   │   │   │   │
(3, 4): ───@───@───@───@───@───@───@───X───────
           │   │   │   │   │   │   │
(3, 5): ───@───@───@───@───@───@───X───────────
           │   │   │   │   │   │
(4, 3): ───@───@───@───@───@───X───────────────
           │   │   │   │   │
(4, 4): ───@───@───@───@───X───────────────────
           │   │   │   │
(4, 5): ───@───@───@───X───────────────────────
           │   │   │
(5, 3): ───@───@───X───────────────────────────
           │   │
(5, 4): ───@───X───────────────────────────────
           │
(5, 5): ───X───────────────────────────────────


In [156]:
c = cirq.decompose(c, keep=keep_func)

ValueError: Operation doesn't satisfy the given `keep` but can't be decomposed: cirq.ControlledOperation(sub_operation=cirq.X(cirq.GridQubit(5, 5)),control_values=((1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,)),controls=(cirq.GridQubit(3, 3), cirq.GridQubit(3, 4), cirq.GridQubit(3, 5), cirq.GridQubit(4, 3), cirq.GridQubit(4, 4), cirq.GridQubit(4, 5), cirq.GridQubit(5, 3), cirq.GridQubit(5, 4)))

In [153]:
print(c)

[cirq.ControlledOperation(sub_operation=cirq.X(cirq.GridQubit(5, 5)),control_values=((1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,)),controls=(cirq.GridQubit(3, 3), cirq.GridQubit(3, 4), cirq.GridQubit(3, 5), cirq.GridQubit(4, 3), cirq.GridQubit(4, 4), cirq.GridQubit(4, 5), cirq.GridQubit(5, 3), cirq.GridQubit(5, 4))), cirq.ControlledOperation(sub_operation=cirq.X(cirq.GridQubit(5, 4)),control_values=((1,), (1,), (1,), (1,), (1,), (1,), (1,)),controls=(cirq.GridQubit(3, 3), cirq.GridQubit(3, 4), cirq.GridQubit(3, 5), cirq.GridQubit(4, 3), cirq.GridQubit(4, 4), cirq.GridQubit(4, 5), cirq.GridQubit(5, 3))), cirq.ControlledOperation(sub_operation=cirq.X(cirq.GridQubit(5, 3)),control_values=((1,), (1,), (1,), (1,), (1,), (1,)),controls=(cirq.GridQubit(3, 3), cirq.GridQubit(3, 4), cirq.GridQubit(3, 5), cirq.GridQubit(4, 3), cirq.GridQubit(4, 4), cirq.GridQubit(4, 5))), cirq.ControlledOperation(sub_operation=cirq.X(cirq.GridQubit(4, 5)),control_values=((1,), (1,), (1,), (1,), (1,)),controls=

In [157]:
g = cirq.CCX.on(*cirq.LineQubit.range(3))

In [158]:
print(g)

TOFFOLI(0, 1, 2)


In [159]:
print(cirq.decompose(g))

[(cirq.Y**0.5).on(cirq.LineQubit(2)), cirq.XPowGate(exponent=1.0, global_shift=-0.25).on(cirq.LineQubit(2)), cirq.T(cirq.LineQubit(0)), cirq.T(cirq.LineQubit(1)), cirq.T(cirq.LineQubit(2)), (cirq.Y**-0.5).on(cirq.LineQubit(1)), cirq.CZ(cirq.LineQubit(0), cirq.LineQubit(1)), (cirq.Y**0.5).on(cirq.LineQubit(1)), (cirq.Y**-0.5).on(cirq.LineQubit(2)), cirq.CZ(cirq.LineQubit(1), cirq.LineQubit(2)), (cirq.Y**0.5).on(cirq.LineQubit(2)), (cirq.T**-1).on(cirq.LineQubit(1)), cirq.T(cirq.LineQubit(2)), (cirq.Y**-0.5).on(cirq.LineQubit(1)), cirq.CZ(cirq.LineQubit(0), cirq.LineQubit(1)), (cirq.Y**0.5).on(cirq.LineQubit(1)), (cirq.Y**-0.5).on(cirq.LineQubit(2)), cirq.CZ(cirq.LineQubit(1), cirq.LineQubit(2)), (cirq.Y**0.5).on(cirq.LineQubit(2)), (cirq.T**-1).on(cirq.LineQubit(2)), (cirq.Y**-0.5).on(cirq.LineQubit(1)), cirq.CZ(cirq.LineQubit(0), cirq.LineQubit(1)), (cirq.Y**0.5).on(cirq.LineQubit(1)), (cirq.Y**-0.5).on(cirq.LineQubit(2)), cirq.CZ(cirq.LineQubit(1), cirq.LineQubit(2)), (cirq.Y**0.5).on

In [165]:
g = cirq.ControlledGate(cirq.ControlledGate(cirq.Y ** 0.5)).on(*cirq.LineQubit.range(3))
cirq.decompose(g, keep=keep_func)

ValueError: Operation doesn't satisfy the given `keep` but can't be decomposed: cirq.ControlledOperation(sub_operation=(cirq.Y**0.5).on(cirq.LineQubit(2)),control_values=((1,), (1,)),controls=(cirq.LineQubit(0), cirq.LineQubit(1)))

In [167]:
g = cirq.CT

AttributeError: module 'cirq' has no attribute 'CT'

In [438]:
def CNOT_toffoli_decomp(bitset, garbage, t, d):
    target = t
    gates = []
    for i in range(1, len(bitset) - 1):
        gates.append(cirq.CCX(garbage[-i - d], bitset[-i], target))
        target = garbage[-i - d]
    gates.append(cirq.CCX(bitset[0], bitset[1], target))
    for gate in gates:
        yield gate
    gates.reverse()
    for gate in gates[1:]:
        yield gate
    gates.reverse()
    for gate in gates[1:]:
        yield gate
    gates.reverse()
    for gate in gates[1:-1]:
        yield gate
#     yield cirq.CCX(bitset[0], bitset[1], target)
#     if d == 1:
#         for gate in gates[:-1]:
#             yield gate
#     else:
#         for gate in gates:
#             yield gate
    
    
def decompose_large_CNOT(control_qubits, target, ancilla):
    if len(control_qubits) == 0:
        return cirq.X(target)
    
    if len(control_qubits) == 1:
        return cirq.CX(control_qubits[0], target)
    
    if len(control_qubits) == 2:
        return cirq.CCX(control_qubits[0], control_qubits[1], target)
    
#     if len(control_qubits) == 4:
#         return cirq.Circuit([
#          cirq.CCX(control_qubits[0], control_qubits[2], ancilla),
#              cirq.CCX(control_qubits[2], ancilla, target),
#              cirq.CCX(control_qubits[1], control_qubits[3], control_qubits[2]),
#              cirq.CCX(control_qubits[2], ancilla, target),
#              cirq.CCX(control_qubits[1], control_qubits[3], control_qubits[2]),
#              cirq.CCX(control_qubits[0], control_qubits[2], ancilla),
#              cirq.CCX(control_qubits[2], ancilla, target),
#              cirq.CCX(control_qubits[1], control_qubits[3], control_qubits[2]),
#              cirq.CCX(control_qubits[2], ancilla, target),
#              cirq.CCX(control_qubits[1], control_qubits[3], control_qubits[2]),])
    
    bitset1 = [tq for i, tq in enumerate(control_qubits) if i%2 == 0]
    bitset2 = [tq for i, tq in enumerate(control_qubits) if i%2 == 1]
    bitset2.append(ancilla)
    gate1 = CNOT_toffoli_decomp(bitset1, bitset2, ancilla, 1)
    gate2 = CNOT_toffoli_decomp(bitset2, bitset1, target, 0)
    gate3 = CNOT_toffoli_decomp(bitset1, bitset2, ancilla, 1)
    gate4 = CNOT_toffoli_decomp(bitset2, bitset1, target, 0)
    return cirq.Circuit([gate1, gate2, gate3, gate4])


def increment(qubits):
    print(qubits)
    n_qubits = len(qubits)
    ancilla = cirq.LineQubit(5)
    c = cirq.Circuit()
    for i in range(n_qubits):
        print("hi")
        control_qubits = qubits[i + 1:]
        target = qubits[i]
        c.append(decompose_large_CNOT(control_qubits, target, ancilla))
    if n_qubits < 3:
        return c, []
    return c, [ancilla]

In [440]:
qs = cirq.LineQubit.range(7)
ancilla = qs[-1]
target = qs[-2]
# target_qubits = qs[:-2]
c = decompose_large_CNOT(qs[:-2], target, ancilla)
# print(cirq.unitary(c).shape)
# print(cirq.unitary(c))
# with open("unitary.txt", "w") as f:
#     np.savetxt(f, cirq.unitary(c), fmt='%1.1f')
print(c)
    


0: ───────@───────@───────────────────@───────@───────────────
          │       │                   │       │
1: ───────┼───────┼───@───────@───────┼───────┼───@───────@───
          │       │   │       │       │       │   │       │
2: ───────@───────@───┼───────┼───────@───────@───┼───────┼───
          │       │   │       │       │       │   │       │
3: ───@───X───@───X───@───────@───@───X───@───X───@───────@───
      │       │       │       │   │       │       │       │
4: ───@───────@───@───X───@───X───@───────@───@───X───@───X───
      │       │   │       │       │       │   │       │
5: ───┼───────┼───X───────X───────┼───────┼───X───────X───────
      │       │   │       │       │       │   │       │
6: ───X───────X───@───────@───────X───────X───@───────@───────


In [411]:
def increment_unitary(n_qubits):
    input = np.empty((2 ** n_qubits, 2 ** n_qubits))
    input[1:] = np.eye(2 ** n_qubits)[:-1]
    input[:1] = np.eye(2 ** n_qubits)[-1:]
    return input

iu = increment_unitary(4)
print(np.isclose(cirq.kron(iu, np.eye(2)), cirq.unitary(c)).all())

True


In [319]:
print(iu)

[[0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [425]:
n = 5
qs = cirq.LineQubit.range(n)
control_qubits = qs[:-1]
target = qs[-1]
ancilla = cirq.LineQubit(n)

c = decompose_large_CNOT(control_qubits, target, ancilla)
print(cirq.unitary(c))
print(c)

[[1.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 ...
 [0.+0.j 0.+0.j 0.+0.j ... 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]]
0: ───@───────────────────@───
      │                   │
1: ───┼───────@───────@───┼───
      │       │       │   │
2: ───@───@───X───@───X───@───
      │   │   │   │   │   │
3: ───┼───┼───@───┼───@───┼───
      │   │       │       │
4: ───┼───X───────X───────┼───
      │   │       │       │
5: ───X───@───────@───────X───


In [403]:
simulator = cirq.Simulator()
initializations = [cirq.X(qs[1]), cirq.X(qs[2]), cirq.X(qs[3])]
cm = cirq.Circuit([*initializations, c, cirq.measure(*qs), cirq.measure(ancilla)])
result = simulator.run(cm, repetitions=30)
print(result)

0,1,2,3,4=000000000000000000000000000000, 111111111111111111111111111111, 111111111111111111111111111111, 111111111111111111111111111111, 000000000000000000000000000000
5=000000000000000000000000000000


In [413]:
print(cirq.unitary(c))

[[1.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 ...
 [0.+0.j 0.+0.j 0.+0.j ... 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]]


In [426]:
iu = cirq.unitary(cirq.ControlledGate(cirq.ControlledGate(cirq.CCX)).on(*cirq.LineQubit.range(5)))
ku = cirq.kron(np.eye(2), iu)
print(np.isclose(ku, cirq.unitary(c)).all())

False


In [424]:
c = cirq.Circuit(cirq.ControlledGate(cirq.ControlledGate(cirq.CCX)).on(*cirq.LineQubit.range(5)))
print(c)

0: ───@───
      │
1: ───@───
      │
2: ───@───
      │
3: ───@───
      │
4: ───X───


In [443]:
len(cirq.decompose(cirq.CCX.on(*cirq.LineQubit.range(3))))

35

In [445]:
np.isclose(np.ones(len(cirq.unitary(c).diagonal())), 1).all()

True

In [ ]:
if np.isclose(matrix.diagonal(), np.ones(len(matrix.diagonal()))).all()
            return cirq.IdentityGate(num_qubits = len(matrix.diagonal())).on(*target_qubits), []

In [449]:
print(cirq.Circuit(cirq.CCZ.on(*cirq.LineQubit.range(3))))

0: ───@───
      │
1: ───@───
      │
2: ───@───


In [450]:
yield cirq.ControlledGate(Y ** -0.5).on(qs[0], qs[2])
yield cirq.CCZ.on(qs[0], qs[1], qs[2])
yield cirq.ControlledGate(Y ** 0.)
yield cirq.ControlledGate(Y ** 0.5).on(qs[0], qs[1])
yield cirq.CX.on(qs[0], qs[1])
yield cirq.ControlledGate(Y ** -0.5).on(qs[0], qs[1])
yield cirq.CCZ(qs[0], qs[1], qs[2])
yield cirq.ControlledGate(Y**0.5).on(qs[0], qs[1])
yield cirq.ControlledGate(T).on(qs[0], qs[1])
yield cirq.ControlledGate(Y**-0.5).on(qs[0], qs[1])
yield cirq.CCZ(qs[0], qs[1], qs[2])
yield cirq.ControlledGate(Y**0.5).on(qs[0], qs[1])
yield cirq.ControlledGate(T ** -1).on(qs[0], qs[1])
yield cirq.ControlledGate(Y**0.5).on(qs[0], qs[1])
yield cirq.CX.on(qs[0], qs[1])
yield cirq.ControlledGate(Y ** -0.5).on(qs[0], qs[2])
yield cirq.CCZ.on(qs[0], qs[1], qs[2])
yield cirq.ControlledGate(Y ** 0.5).on(qs[0], qs[2])

SyntaxError: 'yield' outside function (<ipython-input-450-a02674774006>, line 1)

In [466]:
g = (cirq.ISWAP ** 0.5).on(*cirq.LineQubit.range(2))
g = cirq.decompose(g)
print(g)
c = cirq.Circuit(g)
print(c)
xmon_converter = cirq.google.ConvertToXmonGates()

[(cirq.Y**-0.5).on(cirq.LineQubit(1)), cirq.CZ(cirq.LineQubit(0), cirq.LineQubit(1)), (cirq.Y**0.5).on(cirq.LineQubit(1)), (cirq.Y**0.5).on(cirq.LineQubit(0)), cirq.XPowGate(exponent=1.0, global_shift=-0.25).on(cirq.LineQubit(0)), (cirq.Y**-0.5).on(cirq.LineQubit(0)), cirq.CZ(cirq.LineQubit(1), cirq.LineQubit(0)), (cirq.Y**0.5).on(cirq.LineQubit(0)), cirq.T(cirq.LineQubit(0)), (cirq.Y**-0.5).on(cirq.LineQubit(0)), cirq.CZ(cirq.LineQubit(1), cirq.LineQubit(0)), (cirq.Y**0.5).on(cirq.LineQubit(0)), (cirq.T**-1).on(cirq.LineQubit(0)), (cirq.Y**0.5).on(cirq.LineQubit(0)), cirq.XPowGate(exponent=1.0, global_shift=-0.25).on(cirq.LineQubit(0)), (cirq.Y**-0.5).on(cirq.LineQubit(1)), cirq.CZ(cirq.LineQubit(0), cirq.LineQubit(1)), (cirq.Y**0.5).on(cirq.LineQubit(1))]
0: ────────────@───Y^0.5───X───Y^-0.5───@───Y^0.5───T───Y^-0.5───@───Y^0.5────T^-1───Y^0.5───X───@───────────
               │                        │                        │                               │
1: ───Y^-0.5───@───Y^0.

In [512]:
def is_adjacent(q1, q2):
    return (q1.row == q2.row and np.abs(q1.col - q2.col) == 1) or (np.abs(q1.row - q2.row) == 1 and q1.col == q2.col)

def swap_path(qs, q1, q2):
    path = []
    if q1 == q2:
        return path
    q = q1
    while not is_adjacent(q, q2):
        if not q2.row - q.row == 0:
            row_dir = int((q2.row - q.row)/np.abs(q2.row - q.row))
            if cirq.GridQubit(q.row + row_dir, q.col) in qs:
                q = cirq.GridQubit(q.row + row_dir, q.col)
                path.append(q)
                continue
        if not q2.col - q.col == 0:
            col_dir = int((q2.col - q.col)/np.abs(q2.col - q.col))
            q = cirq.GridQubit(q.row, q.col + col_dir)
            path.append(q)
    return path

In [513]:
qs = cirq.GridQubit.square(int(np.sqrt(16)), 3, 3)
q1 = qs[0]
q2 = qs[7]
print(q1)
print(q2)
sp = swap_path(qs, qs[0], qs[7])

(3, 3)
(4, 6)


In [514]:
print(q1)
print(q2)
print(sp)

(3, 3)
(4, 6)
[cirq.GridQubit(4, 3), cirq.GridQubit(4, 4), cirq.GridQubit(4, 5)]


In [515]:
def two_q_sycamore(g, q1, q2, qs):
    sp = swap_path(qs, q1, q2)
    if len(sp) == 0:
        yield g(q1, q2)
        return
    q = q1
    for i in range(len(sp)):
        yield cirq.SWAP(q, sp[i])
        q = sp[i]
    yield g.on(q, q2)
    sp.reverse()
    for i in range(1, len(sp)):
        yield cirq.SWAP(q, sp[i])
        q = sp[i]
    yield cirq.SWAP(q, q1)
    
q1 = qs[2]
q2 = qs[1]
    
c = cirq.Circuit(two_q_sycamore(cirq.CX, q1, q2, qs))

In [508]:
print(c)

(3, 4): ───X───
           │
(3, 5): ───@───


In [492]:
g = cirq.CX(*cirq.LineQubit.range(2))
print(g.qubits)

(cirq.LineQubit(0), cirq.LineQubit(1))


In [517]:
g = cirq.SWAP(*cirq.LineQubit.range(2))
converter.convert(g)

[cirq.PhasedXPowGate(phase_exponent=0.44650378384076217, exponent=0.8817921214052824).on(cirq.LineQubit(0)),
 cirq.PhasedXPowGate(phase_exponent=-0.7656774060816165, exponent=0.6628666504604785).on(cirq.LineQubit(1)),
 cirq.google.SYC(cirq.LineQubit(0), cirq.LineQubit(1)),
 cirq.PhasedXPowGate(phase_exponent=-0.6277589946716742, exponent=0.5659160932099687).on(cirq.LineQubit(0)),
 cirq.google.SYC(cirq.LineQubit(0), cirq.LineQubit(1)),
 cirq.PhasedXPowGate(phase_exponent=0.28890767199499257, exponent=0.4340839067900317).on(cirq.LineQubit(1)),
 cirq.PhasedXPowGate(phase_exponent=-0.22592784059288928).on(cirq.LineQubit(0)),
 cirq.google.SYC(cirq.LineQubit(0), cirq.LineQubit(1)),
 cirq.PhasedXPowGate(phase_exponent=-0.4691261557936808, exponent=0.7728525693920243).on(cirq.LineQubit(0)),
 cirq.PhasedXPowGate(phase_exponent=-0.8150261316932077, exponent=0.11820787859471782).on(cirq.LineQubit(1)),
 (cirq.Z**-0.7384700844660306).on(cirq.LineQubit(1)),
 (cirq.Z**-0.7034535141382525).on(cirq.Lin

In [547]:
def controlled_sqrt_iswap(qs):
    c = cirq.Circuit()
    c.append(cirq.ControlledGate(cirq.Y ** -0.5).on(qs[0], qs[2]))
    c.append(cirq.CCZ.on(qs[0], qs[1], qs[2]))
    c.append(cirq.ControlledGate(cirq.Y ** 0.5).on(qs[0], qs[2]))
    c.append(cirq.ControlledGate(cirq.Y ** 0.5).on(qs[0], qs[1]))
    c.append(cirq.CX.on(qs[0], qs[1]))
    c.append(cirq.ControlledGate(cirq.Y ** -0.5).on(qs[0], qs[1]))
    c.append(cirq.CCZ(qs[0], qs[1], qs[2]))
    c.append(cirq.ControlledGate(cirq.Y**0.5).on(qs[0], qs[1]))
    c.append(cirq.ControlledGate(cirq.T).on(qs[0], qs[1]))
    c.append(cirq.ControlledGate(cirq.Y**-0.5).on(qs[0], qs[1]))
    c.append(cirq.CCZ(qs[0], qs[1], qs[2]))
    c.append(cirq.ControlledGate(cirq.Y ** -0.5).on(qs[0], qs[2]))
    c.append(cirq.ControlledGate(cirq.Y**0.5).on(qs[0], qs[1]))
    c.append(cirq.ControlledGate(cirq.T ** -1).on(qs[0], qs[1]))
    c.append(cirq.ControlledGate(cirq.Y**0.5).on(qs[0], qs[1]))
    c.append(cirq.CX.on(qs[0], qs[1]))
    c.append(cirq.CCZ.on(qs[0], qs[1], qs[2]))
    c.append(cirq.ControlledGate(cirq.Y ** 0.5).on(qs[0], qs[2]))
    return c

c2 = controlled_sqrt_iswap(cirq.LineQubit.range(3))

In [548]:
print(cirq.unitary(c))

[[1.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j]
 [0.        +0.00000000e+00j 1.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j]
 [0.        +0.00000000e+00j 0.        +0.00000000e+00j
  1.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j]
 [0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 1.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j]
 [0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00

In [546]:
g = cirq.ControlledGate(cirq.ISWAP ** 0.5)
g = cirq.decompose(g.on(*cirq.LineQubit.range(3)))
c = cirq.Circuit(g)
print(cirq.unitary(c))
print(cirq.unitary(c2))
print(c)
print(np.isclose(cirq.unitary(c), cirq.unitary(c2)))

[[1.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j]
 [0.        +0.00000000e+00j 1.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j]
 [0.        +0.00000000e+00j 0.        +0.00000000e+00j
  1.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j]
 [0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 1.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j]
 [0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00

In [530]:
u = cirq.unitary(cirq.ControlledGate(cirq.ISWAP ** 0.5))
print(svd(u))

(array([[ 1.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ],
       [ 0.        +0.j        ,  1.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         1.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  1.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         

In [526]:
print(c)

0: ───@────────@───@───────@───────@───@────────@───@───────@───@────────@───@────────@───────@──────@───────@───@───@───────
      │        │   │       │       │   │        │   │       │   │        │   │        │       │      │       │   │   │
1: ───┼────────@───┼───────Y^0.5───X───Y^-0.5───@───Y^0.5───T───Y^-0.5───@───┼────────Y^0.5───T^-1───Y^0.5───X───@───┼───────
      │        │   │                            │                        │   │                                   │   │
2: ───Y^-0.5───@───Y^0.5────────────────────────@────────────────────────@───Y^-0.5──────────────────────────────@───Y^0.5───


In [550]:
g = cirq.ControlledGate(cirq.FSimGate(-np.pi/4, 0))
cirq.decompose(g.on(*cirq.LineQubit.range(3)))

[cirq.XXPowGate(exponent=-0.25, global_shift=-0.5).on(cirq.LineQubit(1), cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0)),
 cirq.YYPowGate(exponent=-0.25, global_shift=-0.5).on(cirq.LineQubit(1), cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0)),
 (cirq.CZ**-0.0).on(cirq.LineQubit(1), cirq.LineQubit(2)).controlled_by(cirq.LineQubit(0))]